# Generated by Django 4.0.3 on 2022-05-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cctv_china_news',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('version_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='新闻日期')),
                ('title', models.CharField(blank=True, max_length=1000, null=True, verbose_name='标题')),
                ('brief', models.CharField(blank=True, max_length=1000, null=True, verbose_name='概要')),
                ('keyword', models.CharField(blank=True, max_length=1000, null=True, verbose_name='关键词')),
                ('url', models.CharField(blank=True, max_length=1000, null=True, verbose_name='网页连接')),
                ('refresh_date', models.CharField(blank=True, max_length=100, null=True, verbose_name='入库时间')),
                ('news_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='新闻类别')),
            ],
            options={
                'verbose_name': '央视国内新闻',
                'verbose_name_plural': '央视国内新闻',
                'db_table': 'tbl_d_news_cctv_china',
            },
        ),
        migrations.CreateModel(
            name='cctv_economy_news',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('version_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='新闻日期')),
                ('title', models.CharField(blank=True, max_length=1000, null=True, verbose_name='标题')),
                ('brief', models.CharField(blank=True, max_length=1000, null=True, verbose_name='概要')),
                ('keyword', models.CharField(blank=True, max_length=1000, null=True, verbose_name='关键词')),
                ('url', models.CharField(blank=True, max_length=1000, null=True, verbose_name='网页连接')),
                ('refresh_date', models.CharField(blank=True, max_length=100, null=True, verbose_name='入库时间')),
                ('news_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='新闻类别')),
            ],
            options={
                'verbose_name': '央视经济新闻',
                'verbose_name_plural': '央视经济新闻',
                'db_table': 'tbl_d_news_cctv_economy',
            },
        ),
        migrations.CreateModel(
            name='cctv_world_news',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('version_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='新闻日期')),
                ('title', models.CharField(blank=True, max_length=1000, null=True, verbose_name='标题')),
                ('brief', models.CharField(blank=True, max_length=1000, null=True, verbose_name='概要')),
                ('keyword', models.CharField(blank=True, max_length=1000, null=True, verbose_name='关键词')),
                ('url', models.CharField(blank=True, max_length=1000, null=True, verbose_name='网页连接')),
                ('refresh_date', models.CharField(blank=True, max_length=100, null=True, verbose_name='入库时间')),
                ('news_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='新闻类别')),
            ],
            options={
                'verbose_name': '央视国际新闻',
                'verbose_name_plural': '央视国际新闻',
                'db_table': 'tbl_d_news_cctv_world',
            },
        ),
        migrations.CreateModel(
            name='gold_data',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('item', models.CharField(blank=True, max_length=100, null=True, verbose_name='类别')),
                ('open', models.CharField(blank=True, max_length=100, null=True, verbose_name='开盘价')),
                ('high', models.CharField(blank=True, max_length=100, null=True, verbose_name='最高价')),
                ('low', models.CharField(blank=True, max_length=100, null=True, verbose_name='最低价')),
                ('close', models.CharField(blank=True, max_length=100, null=True, verbose_name='收盘价')),
                ('up_or_down', models.CharField(blank=True, max_length=100, null=True, verbose_name='涨幅')),
                ('version_date', models.BigIntegerField(verbose_name='涨幅')),
            ],
            options={
                'verbose_name': '黄金价格',
                'verbose_name_plural': '黄金价格',
                'db_table': 'temp_gold_data',
            },
        ),
        migrations.CreateModel(
            name='lottery_seven_star',
            fields=[
                ('version_date', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='开奖之间')),
                ('number_01', models.CharField(blank=True, max_length=1, null=True, verbose_name='号码1')),
                ('number_02', models.CharField(blank=True, max_length=1, null=True, verbose_name='号码2')),
                ('number_03', models.CharField(blank=True, max_length=1, null=True, verbose_name='号码3')),
                ('number_04', models.CharField(blank=True, max_length=1, null=True, verbose_name='号码4')),
                ('number_05', models.CharField(blank=True, max_length=1, null=True, verbose_name='号码5')),
                ('number_06', models.CharField(blank=True, max_length=1, null=True, verbose_name='号码6')),
                ('final_number', models.CharField(blank=True, max_length=1, null=True, verbose_name='特别号码')),
            ],
            options={
                'verbose_name': '彩票-七星彩',
                'verbose_name_plural': '彩票-七星彩',
                'db_table': 'tbl_d_lottery_seven',
            },
        ),
        migrations.CreateModel(
            name='non_farm',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('version_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='日期')),
                ('current_value', models.CharField(blank=True, max_length=20, null=True, verbose_name='当前值')),
                ('predict_value', models.CharField(blank=True, max_length=20, null=True, verbose_name='预测值')),
                ('previous_value', models.CharField(blank=True, max_length=20, null=True, verbose_name='上一期值')),
                ('refresh_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '非农数据',
                'verbose_name_plural': '非农数据',
                'db_table': 'tbl_non_farm_data',
            },
        ),
    ]
