# Generated by Django 4.0.3 on 2022-04-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0003_alter_non_farm_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='cctv_world_news',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('version_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='新闻日期')),
                ('title', models.CharField(blank=True, max_length=1000, null=True, verbose_name='标题')),
                ('brief', models.CharField(blank=True, max_length=1000, null=True, verbose_name='概要')),
                ('keyword', models.CharField(blank=True, max_length=100, null=True, verbose_name='关键词')),
                ('url', models.CharField(blank=True, max_length=500, null=True, verbose_name='网页连接')),
                ('refresh_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='入库时间')),
            ],
            options={
                'verbose_name': '央视国际新闻',
                'verbose_name_plural': '央视国际新闻',
                'db_table': 'tbl_news_cctv_world',
            },
        ),
    ]
