# Generated by Django 4.0.3 on 2022-04-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0004_cctv_world_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cctv_world_news',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='cctv_world_news',
            name='keyword',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='关键词'),
        ),
        migrations.AlterField(
            model_name='cctv_world_news',
            name='refresh_date',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='入库时间'),
        ),
        migrations.AlterField(
            model_name='cctv_world_news',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='网页连接'),
        ),
        migrations.AlterModelTable(
            name='cctv_world_news',
            table='tbl_d_news_cctv_world',
        ),
    ]
