# Generated by Django 4.0.3 on 2022-04-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0007_cctv_economy_news_alter_cctv_china_news_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cctv_china_news',
            name='news_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='新闻类别'),
        ),
        migrations.AddField(
            model_name='cctv_economy_news',
            name='news_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='新闻类别'),
        ),
        migrations.AddField(
            model_name='cctv_world_news',
            name='news_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='新闻类别'),
        ),
    ]
